/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Invitations: () => import('#controllers/auth/invitations_controller'),
  },
  Components: () => import('#controllers/components_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Inventory: () => import('#controllers/inventory_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  Invoices: () => import('#controllers/invoices_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  Materials: () => import('#controllers/materials_controller'),
  Pos: () => import('#controllers/pos_controller'),
  ProductCategories: () => import('#controllers/product_categories_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Purchases: () => import('#controllers/purchases_controller'),
  Quotations: () => import('#controllers/quotations_controller'),
  Reports: () => import('#controllers/reports_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Sales: () => import('#controllers/sales_controller'),
  Session: () => import('#controllers/session_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
  Users: () => import('#controllers/users_controller'),
}
