/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedBy', 'roleId', 'status', 'token', 'type', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedBy: number | null
  @column()
  declare roleId: number
  @column()
  declare status: string
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ResourceGrantSchema extends BaseModel {
  static $columns = ['actions', 'createdAt', 'expiresAt', 'grantedBy', 'id', 'resourceId', 'resourceType', 'updatedAt', 'userId'] as const
  $columns = ResourceGrantSchema.$columns
  @column()
  declare actions: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantedBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare resourceId: string
  @column()
  declare resourceType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'displayName', 'id', 'isSystem', 'name', 'parentRoleId', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean | null
  @column()
  declare name: string
  @column()
  declare parentRoleId: number | null
  @column()
  declare permissions: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'roleId', 'updatedAt', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarKey', 'createdAt', 'email', 'firstName', 'fullName', 'id', 'isOwner', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarKey: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOwner: boolean | null
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
