/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'updatedAt', 'updatedBy', 'value'] as const
  $columns = AppSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
  @column()
  declare value: string
}

export class AuditEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'id', 'occurredAt', 'payload', 'targetId', 'targetType'] as const
  $columns = AuditEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare payload: any | null
  @column()
  declare targetId: number | null
  @column()
  declare targetType: string | null
}

export class CashSessionSchema extends BaseModel {
  static $columns = ['closedAt', 'closedByUserId', 'countedCash', 'createdAt', 'expectedCash', 'id', 'note', 'number', 'openedAt', 'openedByUserId', 'openingFloat', 'status', 'updatedAt', 'variance'] as const
  $columns = CashSessionSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare closedByUserId: number | null
  @column()
  declare countedCash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expectedCash: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare openedByUserId: number | null
  @column()
  declare openingFloat: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare variance: string | null
}

export class ComponentSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultSupplierId', 'defaultUnitCost', 'id', 'imageKey', 'isActive', 'name', 'reorderThresholdQty', 'sku', 'unit', 'updatedAt'] as const
  $columns = ComponentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultSupplierId: number | null
  @column()
  declare defaultUnitCost: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageKey: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare reorderThresholdQty: number | null
  @column()
  declare sku: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerSchema extends BaseModel {
  static $columns = ['billingAddress', 'createdAt', 'creditLimit', 'email', 'gstin', 'id', 'isActive', 'name', 'phone', 'shippingAddress', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare billingAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditLimit: string | null
  @column()
  declare email: string | null
  @column()
  declare gstin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare shippingAddress: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DocSequenceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastNumber', 'scope', 'updatedAt', 'year'] as const
  $columns = DocSequenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastNumber: bigint | number
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare year: number
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'createdByUserId', 'description', 'id', 'incurredAt', 'jobId', 'kind', 'machineId', 'updatedAt'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare incurredAt: DateTime
  @column()
  declare jobId: number | null
  @column()
  declare kind: string
  @column()
  declare machineId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class IdempotencyKeySchema extends BaseModel {
  static $columns = ['actorUserId', 'createdAt', 'expiresAt', 'id', 'key', 'responseBody', 'responseStatus', 'route'] as const
  $columns = IdempotencyKeySchema.$columns
  @column()
  declare actorUserId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare responseBody: any | null
  @column()
  declare responseStatus: number
  @column()
  declare route: string
}

export class InventorySchema extends BaseModel {
  static $columns = ['avgUnitCost', 'createdAt', 'id', 'itemId', 'itemKind', 'qty', 'updatedAt'] as const
  $columns = InventorySchema.$columns
  @column()
  declare avgUnitCost: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare qty: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedBy', 'roleId', 'status', 'token', 'type', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedBy: number | null
  @column()
  declare roleId: number
  @column()
  declare status: string
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvoiceItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'invoiceId', 'lineSubtotal', 'lineTax', 'lineTotal', 'productId', 'qty', 'taxRatePct', 'unitPrice', 'updatedAt'] as const
  $columns = InvoiceItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column()
  declare lineSubtotal: string
  @column()
  declare lineTax: string
  @column()
  declare lineTotal: string
  @column()
  declare productId: number | null
  @column()
  declare qty: number
  @column()
  declare taxRatePct: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvoicePaymentSchema extends BaseModel {
  static $columns = ['amount', 'cashSessionId', 'createdAt', 'id', 'invoiceId', 'method', 'paidAt', 'recordedByUserId', 'reference', 'updatedAt'] as const
  $columns = InvoicePaymentSchema.$columns
  @column()
  declare amount: string
  @column()
  declare cashSessionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column()
  declare method: string
  @column.dateTime()
  declare paidAt: DateTime
  @column()
  declare recordedByUserId: number | null
  @column()
  declare reference: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'creditTotal', 'customerId', 'dueAt', 'id', 'issuedAt', 'number', 'orderId', 'paidTotal', 'pdfKey', 'replacesInvoiceId', 'status', 'subtotal', 'taxTotal', 'total', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare creditTotal: string
  @column()
  declare customerId: number
  @column.dateTime()
  declare dueAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare issuedAt: DateTime
  @column()
  declare number: string
  @column()
  declare orderId: number
  @column()
  declare paidTotal: string
  @column()
  declare pdfKey: string | null
  @column()
  declare replacesInvoiceId: number | null
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare taxTotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class JobMaterialConsumptionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'id', 'itemId', 'itemKind', 'jobId', 'lineCost', 'qtyConsumed', 'qtyReturned', 'qtyWasted', 'reason', 'unitCostAtConsume'] as const
  $columns = JobMaterialConsumptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare jobId: number
  @column()
  declare lineCost: string
  @column()
  declare qtyConsumed: string
  @column()
  declare qtyReturned: string
  @column()
  declare qtyWasted: string
  @column()
  declare reason: string
  @column()
  declare unitCostAtConsume: string
}

export class JobWorkerSchema extends BaseModel {
  static $columns = ['assignedAt', 'createdAt', 'hourlyRateAtAssign', 'id', 'jobId', 'lineCost', 'minutesWorked', 'releasedAt', 'updatedAt', 'workerId'] as const
  $columns = JobWorkerSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hourlyRateAtAssign: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobId: number
  @column()
  declare lineCost: string
  @column()
  declare minutesWorked: number
  @column.dateTime()
  declare releasedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare workerId: number
}

export class MachineSchema extends BaseModel {
  static $columns = ['acquiredAt', 'createdAt', 'currentJobId', 'hourlyRate', 'id', 'model', 'name', 'notes', 'purchaseItemId', 'serialNumber', 'status', 'updatedAt'] as const
  $columns = MachineSchema.$columns
  @column.dateTime()
  declare acquiredAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentJobId: number | null
  @column()
  declare hourlyRate: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare purchaseItemId: number | null
  @column()
  declare serialNumber: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultSupplierId', 'defaultUnitCost', 'id', 'imageKey', 'isActive', 'name', 'reorderThresholdG', 'sku', 'type', 'unit', 'updatedAt'] as const
  $columns = MaterialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultSupplierId: number | null
  @column()
  declare defaultUnitCost: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageKey: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare reorderThresholdG: string | null
  @column()
  declare sku: string
  @column()
  declare type: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'lineSubtotal', 'lineTax', 'lineTotal', 'orderId', 'productId', 'qty', 'taxRatePct', 'unitPrice', 'updatedAt'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineSubtotal: string
  @column()
  declare lineTax: string
  @column()
  declare lineTotal: string
  @column()
  declare orderId: number
  @column()
  declare productId: number | null
  @column()
  declare qty: number
  @column()
  declare taxRatePct: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderReturnItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'lineSubtotal', 'lineTax', 'lineTotal', 'orderItemId', 'orderReturnId', 'productId', 'qty', 'taxRatePct', 'unitPrice', 'updatedAt'] as const
  $columns = OrderReturnItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineSubtotal: string
  @column()
  declare lineTax: string
  @column()
  declare lineTotal: string
  @column()
  declare orderItemId: number
  @column()
  declare orderReturnId: number
  @column()
  declare productId: number | null
  @column()
  declare qty: number
  @column()
  declare taxRatePct: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderReturnSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'creditApplied', 'customerId', 'id', 'invoiceId', 'note', 'number', 'orderId', 'refundAmount', 'refundMethod', 'subtotal', 'taxTotal', 'total', 'updatedAt'] as const
  $columns = OrderReturnSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare creditApplied: string
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number | null
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare orderId: number
  @column()
  declare refundAmount: string
  @column()
  declare refundMethod: string | null
  @column()
  declare subtotal: string
  @column()
  declare taxTotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderSchema extends BaseModel {
  static $columns = ['confirmedAt', 'createdAt', 'createdByUserId', 'customerId', 'id', 'note', 'number', 'quotationId', 'status', 'subtotal', 'taxTotal', 'total', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare quotationId: number | null
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare taxTotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductAttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'fileKey', 'id', 'kind', 'mimeType', 'originalName', 'productId', 'sizeBytes', 'sortOrder', 'updatedAt', 'uploadedByUserId'] as const
  $columns = ProductAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare mimeType: string | null
  @column()
  declare originalName: string
  @column()
  declare productId: number
  @column()
  declare sizeBytes: bigint | number
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedByUserId: number | null
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'defaultProfitPct', 'id', 'isActive', 'name', 'taxRatePct', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultProfitPct: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare taxRatePct: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductRecipeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isCurrent', 'itemId', 'itemKind', 'learnedFromJobId', 'productId', 'qtyPerUnit', 'updatedAt', 'version'] as const
  $columns = ProductRecipeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCurrent: boolean
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare learnedFromJobId: number | null
  @column()
  declare productId: number
  @column()
  declare qtyPerUnit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: number
}

export class ProductionJobStageSchema extends BaseModel {
  static $columns = ['autoCompleteAt', 'completedAt', 'createdAt', 'estimatedDurationMin', 'id', 'jobId', 'name', 'sequence', 'startedAt', 'status', 'updatedAt'] as const
  $columns = ProductionJobStageSchema.$columns
  @column.dateTime()
  declare autoCompleteAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estimatedDurationMin: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobId: number
  @column()
  declare name: string
  @column()
  declare sequence: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductionJobSchema extends BaseModel {
  static $columns = ['autoCompleteAt', 'completedAt', 'createdAt', 'createdByUserId', 'currentStageId', 'estimatedDurationMin', 'id', 'labourMinutes', 'machineId', 'machineMinutes', 'note', 'number', 'parentJobId', 'pausedAt', 'plannedQty', 'producedQty', 'productId', 'remainingSeconds', 'startedAt', 'status', 'totalComponentCost', 'totalCost', 'totalExpense', 'totalLabourCost', 'totalMachineCost', 'totalMaterialCost', 'unitCost', 'updatedAt'] as const
  $columns = ProductionJobSchema.$columns
  @column.dateTime()
  declare autoCompleteAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare currentStageId: number | null
  @column()
  declare estimatedDurationMin: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labourMinutes: number
  @column()
  declare machineId: number | null
  @column()
  declare machineMinutes: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare parentJobId: number | null
  @column.dateTime()
  declare pausedAt: DateTime | null
  @column()
  declare plannedQty: number
  @column()
  declare producedQty: number
  @column()
  declare productId: number
  @column()
  declare remainingSeconds: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalComponentCost: string
  @column()
  declare totalCost: string
  @column()
  declare totalExpense: string
  @column()
  declare totalLabourCost: string
  @column()
  declare totalMachineCost: string
  @column()
  declare totalMaterialCost: string
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'defaultProfitPct', 'defaultSalePrice', 'defaultSalePriceSetAt', 'defaultSalePriceSetByUserId', 'defaultSalePriceSourceJobId', 'description', 'id', 'imageKey', 'isActive', 'name', 'sku', 'taxRatePct', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultProfitPct: string | null
  @column()
  declare defaultSalePrice: string | null
  @column.dateTime()
  declare defaultSalePriceSetAt: DateTime | null
  @column()
  declare defaultSalePriceSetByUserId: number | null
  @column()
  declare defaultSalePriceSourceJobId: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageKey: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare sku: string
  @column()
  declare taxRatePct: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'itemKind', 'lineSubtotal', 'lineTax', 'lineTotal', 'purchaseId', 'qty', 'taxRatePct', 'unitCost', 'updatedAt'] as const
  $columns = PurchaseItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare lineSubtotal: string
  @column()
  declare lineTax: string
  @column()
  declare lineTotal: string
  @column()
  declare purchaseId: number
  @column()
  declare qty: string
  @column()
  declare taxRatePct: string
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchasePaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'method', 'note', 'paidAt', 'purchaseId', 'recordedByUserId', 'reference', 'updatedAt'] as const
  $columns = PurchasePaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column()
  declare note: string | null
  @column.dateTime()
  declare paidAt: DateTime
  @column()
  declare purchaseId: number
  @column()
  declare recordedByUserId: number | null
  @column()
  declare reference: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseReturnItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'itemKind', 'lineTotal', 'purchaseItemId', 'purchaseReturnId', 'qty', 'unitCost', 'updatedAt'] as const
  $columns = PurchaseReturnItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare lineTotal: string
  @column()
  declare purchaseItemId: number
  @column()
  declare purchaseReturnId: number
  @column()
  declare qty: string
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseReturnSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'id', 'note', 'number', 'purchaseId', 'supplierId', 'total', 'updatedAt'] as const
  $columns = PurchaseReturnSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare purchaseId: number
  @column()
  declare supplierId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PurchaseSchema extends BaseModel {
  static $columns = ['attachmentKey', 'cancelledAt', 'cancelledByUserId', 'confirmedAt', 'confirmedByUserId', 'createdAt', 'createdByUserId', 'id', 'note', 'number', 'paidTotal', 'purchasedAt', 'status', 'subtotal', 'supplierId', 'taxTotal', 'total', 'updatedAt'] as const
  $columns = PurchaseSchema.$columns
  @column()
  declare attachmentKey: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledByUserId: number | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare confirmedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare paidTotal: string
  @column.dateTime()
  declare purchasedAt: DateTime
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare supplierId: number
  @column()
  declare taxTotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuotationItemBomSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'itemKind', 'qty', 'quotationItemId', 'unitCostAtTime', 'updatedAt'] as const
  $columns = QuotationItemBomSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare qty: string
  @column()
  declare quotationItemId: number
  @column()
  declare unitCostAtTime: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuotationItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'lineSubtotal', 'lineTax', 'lineTotal', 'productId', 'profitPctUsed', 'qty', 'quotationId', 'taxRatePct', 'unitPrice', 'updatedAt'] as const
  $columns = QuotationItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineSubtotal: string
  @column()
  declare lineTax: string
  @column()
  declare lineTotal: string
  @column()
  declare productId: number | null
  @column()
  declare profitPctUsed: string | null
  @column()
  declare qty: number
  @column()
  declare quotationId: number
  @column()
  declare taxRatePct: string
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuotationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'convertedToOrderId', 'createdAt', 'createdByUserId', 'customerId', 'id', 'issuedAt', 'note', 'number', 'pdfKey', 'rejectedAt', 'sentAt', 'status', 'subtotal', 'taxTotal', 'total', 'updatedAt', 'validUntil'] as const
  $columns = QuotationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare convertedToOrderId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare issuedAt: DateTime
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare pdfKey: string | null
  @column.dateTime()
  declare rejectedAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column()
  declare taxTotal: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare validUntil: DateTime
}

export class ResourceGrantSchema extends BaseModel {
  static $columns = ['actions', 'createdAt', 'expiresAt', 'grantedBy', 'id', 'resourceId', 'resourceType', 'updatedAt', 'userId'] as const
  $columns = ResourceGrantSchema.$columns
  @column()
  declare actions: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantedBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare resourceId: string
  @column()
  declare resourceType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'displayName', 'id', 'isSystem', 'name', 'parentRoleId', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean | null
  @column()
  declare name: string
  @column()
  declare parentRoleId: number | null
  @column()
  declare permissions: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'id', 'itemId', 'itemKind', 'note', 'qty', 'reason', 'referenceId', 'referenceType', 'unitCost'] as const
  $columns = StockMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare note: string | null
  @column()
  declare qty: string
  @column()
  declare reason: string
  @column()
  declare referenceId: number | null
  @column()
  declare referenceType: string | null
  @column()
  declare unitCost: string
}

export class StockTakeItemSchema extends BaseModel {
  static $columns = ['countedQty', 'createdAt', 'expectedQty', 'id', 'itemId', 'itemKind', 'stockTakeId', 'unitCost', 'updatedAt'] as const
  $columns = StockTakeItemSchema.$columns
  @column()
  declare countedQty: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expectedQty: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare itemKind: string
  @column()
  declare stockTakeId: number
  @column()
  declare unitCost: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class StockTakeSchema extends BaseModel {
  static $columns = ['completedAt', 'completedByUserId', 'createdAt', 'createdByUserId', 'id', 'note', 'number', 'status', 'updatedAt'] as const
  $columns = StockTakeSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare completedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare number: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SupplierSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'gstin', 'id', 'isActive', 'name', 'phone', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare gstin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'roleId', 'updatedAt', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarKey', 'createdAt', 'email', 'firstName', 'fullName', 'id', 'isOwner', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarKey: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOwner: boolean | null
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkerPaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'createdByUserId', 'id', 'kind', 'note', 'paidAt', 'periodEnd', 'periodStart', 'updatedAt', 'workerId'] as const
  $columns = WorkerPaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare note: string | null
  @column.dateTime()
  declare paidAt: DateTime
  @column.date()
  declare periodEnd: DateTime | null
  @column.date()
  declare periodStart: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare workerId: number
}

export class WorkerSchema extends BaseModel {
  static $columns = ['createdAt', 'currentJobId', 'hourlyRate', 'id', 'joinedAt', 'monthlySalary', 'name', 'notes', 'payType', 'phone', 'standardMonthlyHours', 'status', 'updatedAt'] as const
  $columns = WorkerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentJobId: number | null
  @column()
  declare hourlyRate: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column()
  declare monthlySalary: string
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare payType: string
  @column()
  declare phone: string | null
  @column()
  declare standardMonthlyHours: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
