import * as React from 'react'
import { Document, Page, Text, View } from '@react-pdf/renderer'
import { styles } from './shared_styles.js'

export type QuotationPdfData = {
  quotation: {
    id: number
    number: string
    status: string
    customer: { id: number; name: string } | null
    issuedAt: string | null
    validUntil: string | null
    subtotal: string
    taxTotal: string
    total: string
    note: string | null
  }
  items: Array<{
    id: number
    description: string
    qty: number
    unitPrice: string
    profitPctUsed: string | null
    taxRatePct: string
    lineSubtotal: string
    lineTax: string
    lineTotal: string
  }>
  appName?: string
}

function fmt(n: string | number): string {
  const v = Number(n)
  if (!Number.isFinite(v)) return String(n)
  return v.toFixed(2)
}

export function QuotationDocument({ quotation, items, appName }: QuotationPdfData) {
  return (
    <Document title={`Quotation ${quotation.number}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>Quotation {quotation.number}</Text>
            <Text style={styles.subtle}>
              Issued {quotation.issuedAt?.slice(0, 10) ?? '—'} · Valid until{' '}
              {quotation.validUntil?.slice(0, 10) ?? '—'}
            </Text>
          </View>
          <View>
            <Text style={styles.badge}>{quotation.status.toUpperCase()}</Text>
            {appName ? (
              <Text style={[styles.subtle, { marginTop: 8, textAlign: 'right' }]}>
                {appName}
              </Text>
            ) : null}
          </View>
        </View>

        <View style={[styles.section, styles.twoCol]}>
          <View style={styles.col}>
            <Text style={styles.sectionTitle}>Customer</Text>
            <Text>{quotation.customer?.name ?? '—'}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.tHead}>
            <Text style={styles.tCellDesc}>Description</Text>
            <Text style={styles.tCellQty}>Qty</Text>
            <Text style={styles.tCellMoney}>Unit price</Text>
            <Text style={styles.tCellTax}>Tax %</Text>
            <Text style={styles.tCellMoney}>Total</Text>
          </View>
          {items.map((it) => (
            <View style={styles.tRow} key={it.id}>
              <Text style={styles.tCellDesc}>{it.description}</Text>
              <Text style={styles.tCellQty}>{it.qty}</Text>
              <Text style={styles.tCellMoney}>{fmt(it.unitPrice)}</Text>
              <Text style={styles.tCellTax}>{fmt(it.taxRatePct)}</Text>
              <Text style={styles.tCellMoney}>{fmt(it.lineTotal)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.totalsBox}>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsLabel}>Subtotal</Text>
            <Text>{fmt(quotation.subtotal)}</Text>
          </View>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsLabel}>Tax</Text>
            <Text>{fmt(quotation.taxTotal)}</Text>
          </View>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsValue}>Total</Text>
            <Text style={styles.totalsValue}>{fmt(quotation.total)}</Text>
          </View>
        </View>

        {quotation.note ? (
          <View style={[styles.section, { marginTop: 18 }]}>
            <Text style={styles.sectionTitle}>Note</Text>
            <Text>{quotation.note}</Text>
          </View>
        ) : null}

        <Text style={styles.footer} fixed>
          Generated by {appName ?? 'Panel'} · quotation {quotation.number}
        </Text>
      </Page>
    </Document>
  )
}
