/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'health': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health']['types'],
  },
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'invitation.show': {
    methods: ["GET","HEAD"],
    pattern: '/invite/:token',
    tokens: [{"old":"/invite/:token","type":0,"val":"invite","end":""},{"old":"/invite/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['invitation.show']['types'],
  },
  'invitation.store': {
    methods: ["POST"],
    pattern: '/invite/:token',
    tokens: [{"old":"/invite/:token","type":0,"val":"invite","end":""},{"old":"/invite/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['invitation.store']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'system.roles': {
    methods: ["GET","HEAD"],
    pattern: '/system/roles',
    tokens: [{"old":"/system/roles","type":0,"val":"system","end":""},{"old":"/system/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['system.roles']['types'],
  },
  'system.invitations': {
    methods: ["GET","HEAD"],
    pattern: '/system/invitations',
    tokens: [{"old":"/system/invitations","type":0,"val":"system","end":""},{"old":"/system/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['system.invitations']['types'],
  },
  'system.users': {
    methods: ["GET","HEAD"],
    pattern: '/system/users',
    tokens: [{"old":"/system/users","type":0,"val":"system","end":""},{"old":"/system/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['system.users']['types'],
  },
  'system.users.update_roles': {
    methods: ["POST"],
    pattern: '/system/users/:id/roles',
    tokens: [{"old":"/system/users/:id/roles","type":0,"val":"system","end":""},{"old":"/system/users/:id/roles","type":0,"val":"users","end":""},{"old":"/system/users/:id/roles","type":1,"val":"id","end":""},{"old":"/system/users/:id/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['system.users.update_roles']['types'],
  },
  'invitations.store': {
    methods: ["POST"],
    pattern: '/invitations',
    tokens: [{"old":"/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['invitations.store']['types'],
  },
  'invitations.resend': {
    methods: ["POST"],
    pattern: '/invitations/:id/resend',
    tokens: [{"old":"/invitations/:id/resend","type":0,"val":"invitations","end":""},{"old":"/invitations/:id/resend","type":1,"val":"id","end":""},{"old":"/invitations/:id/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['invitations.resend']['types'],
  },
  'invitations.revoke': {
    methods: ["POST"],
    pattern: '/invitations/:id/revoke',
    tokens: [{"old":"/invitations/:id/revoke","type":0,"val":"invitations","end":""},{"old":"/invitations/:id/revoke","type":1,"val":"id","end":""},{"old":"/invitations/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['invitations.revoke']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/roles',
    tokens: [{"old":"/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.destroy': {
    methods: ["POST"],
    pattern: '/roles/:id/delete',
    tokens: [{"old":"/roles/:id/delete","type":0,"val":"roles","end":""},{"old":"/roles/:id/delete","type":1,"val":"id","end":""},{"old":"/roles/:id/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/profile',
    tokens: [{"old":"/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.show']['types'],
  },
  'profile.update': {
    methods: ["POST"],
    pattern: '/profile',
    tokens: [{"old":"/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.update']['types'],
  },
  'profile.avatar.update': {
    methods: ["POST"],
    pattern: '/profile/avatar',
    tokens: [{"old":"/profile/avatar","type":0,"val":"profile","end":""},{"old":"/profile/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['profile.avatar.update']['types'],
  },
  'profile.avatar.destroy': {
    methods: ["POST"],
    pattern: '/profile/avatar/delete',
    tokens: [{"old":"/profile/avatar/delete","type":0,"val":"profile","end":""},{"old":"/profile/avatar/delete","type":0,"val":"avatar","end":""},{"old":"/profile/avatar/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['profile.avatar.destroy']['types'],
  },
  'suppliers.index': {
    methods: ["GET","HEAD"],
    pattern: '/suppliers',
    tokens: [{"old":"/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.index']['types'],
  },
  'suppliers.store': {
    methods: ["POST"],
    pattern: '/suppliers',
    tokens: [{"old":"/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.store']['types'],
  },
  'suppliers.update': {
    methods: ["POST"],
    pattern: '/suppliers/:id',
    tokens: [{"old":"/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.update']['types'],
  },
  'suppliers.archive': {
    methods: ["POST"],
    pattern: '/suppliers/:id/archive',
    tokens: [{"old":"/suppliers/:id/archive","type":0,"val":"suppliers","end":""},{"old":"/suppliers/:id/archive","type":1,"val":"id","end":""},{"old":"/suppliers/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['suppliers.archive']['types'],
  },
  'customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/customers',
    tokens: [{"old":"/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.index']['types'],
  },
  'customers.store': {
    methods: ["POST"],
    pattern: '/customers',
    tokens: [{"old":"/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.store']['types'],
  },
  'customers.update': {
    methods: ["POST"],
    pattern: '/customers/:id',
    tokens: [{"old":"/customers/:id","type":0,"val":"customers","end":""},{"old":"/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.update']['types'],
  },
  'customers.archive': {
    methods: ["POST"],
    pattern: '/customers/:id/archive',
    tokens: [{"old":"/customers/:id/archive","type":0,"val":"customers","end":""},{"old":"/customers/:id/archive","type":1,"val":"id","end":""},{"old":"/customers/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['customers.archive']['types'],
  },
  'materials.index': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/materials',
    tokens: [{"old":"/catalog/materials","type":0,"val":"catalog","end":""},{"old":"/catalog/materials","type":0,"val":"materials","end":""}],
    types: placeholder as Registry['materials.index']['types'],
  },
  'materials.store': {
    methods: ["POST"],
    pattern: '/catalog/materials',
    tokens: [{"old":"/catalog/materials","type":0,"val":"catalog","end":""},{"old":"/catalog/materials","type":0,"val":"materials","end":""}],
    types: placeholder as Registry['materials.store']['types'],
  },
  'materials.update': {
    methods: ["POST"],
    pattern: '/catalog/materials/:id',
    tokens: [{"old":"/catalog/materials/:id","type":0,"val":"catalog","end":""},{"old":"/catalog/materials/:id","type":0,"val":"materials","end":""},{"old":"/catalog/materials/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['materials.update']['types'],
  },
  'materials.archive': {
    methods: ["POST"],
    pattern: '/catalog/materials/:id/archive',
    tokens: [{"old":"/catalog/materials/:id/archive","type":0,"val":"catalog","end":""},{"old":"/catalog/materials/:id/archive","type":0,"val":"materials","end":""},{"old":"/catalog/materials/:id/archive","type":1,"val":"id","end":""},{"old":"/catalog/materials/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['materials.archive']['types'],
  },
  'materials.restore': {
    methods: ["POST"],
    pattern: '/catalog/materials/:id/restore',
    tokens: [{"old":"/catalog/materials/:id/restore","type":0,"val":"catalog","end":""},{"old":"/catalog/materials/:id/restore","type":0,"val":"materials","end":""},{"old":"/catalog/materials/:id/restore","type":1,"val":"id","end":""},{"old":"/catalog/materials/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['materials.restore']['types'],
  },
  'materials.image.update': {
    methods: ["POST"],
    pattern: '/catalog/materials/:id/image',
    tokens: [{"old":"/catalog/materials/:id/image","type":0,"val":"catalog","end":""},{"old":"/catalog/materials/:id/image","type":0,"val":"materials","end":""},{"old":"/catalog/materials/:id/image","type":1,"val":"id","end":""},{"old":"/catalog/materials/:id/image","type":0,"val":"image","end":""}],
    types: placeholder as Registry['materials.image.update']['types'],
  },
  'materials.image.destroy': {
    methods: ["POST"],
    pattern: '/catalog/materials/:id/image/delete',
    tokens: [{"old":"/catalog/materials/:id/image/delete","type":0,"val":"catalog","end":""},{"old":"/catalog/materials/:id/image/delete","type":0,"val":"materials","end":""},{"old":"/catalog/materials/:id/image/delete","type":1,"val":"id","end":""},{"old":"/catalog/materials/:id/image/delete","type":0,"val":"image","end":""},{"old":"/catalog/materials/:id/image/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['materials.image.destroy']['types'],
  },
  'components.index': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/components',
    tokens: [{"old":"/catalog/components","type":0,"val":"catalog","end":""},{"old":"/catalog/components","type":0,"val":"components","end":""}],
    types: placeholder as Registry['components.index']['types'],
  },
  'components.store': {
    methods: ["POST"],
    pattern: '/catalog/components',
    tokens: [{"old":"/catalog/components","type":0,"val":"catalog","end":""},{"old":"/catalog/components","type":0,"val":"components","end":""}],
    types: placeholder as Registry['components.store']['types'],
  },
  'components.update': {
    methods: ["POST"],
    pattern: '/catalog/components/:id',
    tokens: [{"old":"/catalog/components/:id","type":0,"val":"catalog","end":""},{"old":"/catalog/components/:id","type":0,"val":"components","end":""},{"old":"/catalog/components/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['components.update']['types'],
  },
  'components.archive': {
    methods: ["POST"],
    pattern: '/catalog/components/:id/archive',
    tokens: [{"old":"/catalog/components/:id/archive","type":0,"val":"catalog","end":""},{"old":"/catalog/components/:id/archive","type":0,"val":"components","end":""},{"old":"/catalog/components/:id/archive","type":1,"val":"id","end":""},{"old":"/catalog/components/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['components.archive']['types'],
  },
  'components.restore': {
    methods: ["POST"],
    pattern: '/catalog/components/:id/restore',
    tokens: [{"old":"/catalog/components/:id/restore","type":0,"val":"catalog","end":""},{"old":"/catalog/components/:id/restore","type":0,"val":"components","end":""},{"old":"/catalog/components/:id/restore","type":1,"val":"id","end":""},{"old":"/catalog/components/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['components.restore']['types'],
  },
  'components.image.update': {
    methods: ["POST"],
    pattern: '/catalog/components/:id/image',
    tokens: [{"old":"/catalog/components/:id/image","type":0,"val":"catalog","end":""},{"old":"/catalog/components/:id/image","type":0,"val":"components","end":""},{"old":"/catalog/components/:id/image","type":1,"val":"id","end":""},{"old":"/catalog/components/:id/image","type":0,"val":"image","end":""}],
    types: placeholder as Registry['components.image.update']['types'],
  },
  'components.image.destroy': {
    methods: ["POST"],
    pattern: '/catalog/components/:id/image/delete',
    tokens: [{"old":"/catalog/components/:id/image/delete","type":0,"val":"catalog","end":""},{"old":"/catalog/components/:id/image/delete","type":0,"val":"components","end":""},{"old":"/catalog/components/:id/image/delete","type":1,"val":"id","end":""},{"old":"/catalog/components/:id/image/delete","type":0,"val":"image","end":""},{"old":"/catalog/components/:id/image/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['components.image.destroy']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products',
    tokens: [{"old":"/catalog/products","type":0,"val":"catalog","end":""},{"old":"/catalog/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/catalog/products',
    tokens: [{"old":"/catalog/products","type":0,"val":"catalog","end":""},{"old":"/catalog/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.show': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products/:id',
    tokens: [{"old":"/catalog/products/:id","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id","type":0,"val":"products","end":""},{"old":"/catalog/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.show']['types'],
  },
  'products.update': {
    methods: ["POST"],
    pattern: '/catalog/products/:id',
    tokens: [{"old":"/catalog/products/:id","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id","type":0,"val":"products","end":""},{"old":"/catalog/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.archive': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/archive',
    tokens: [{"old":"/catalog/products/:id/archive","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/archive","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/archive","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['products.archive']['types'],
  },
  'products.restore': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/restore',
    tokens: [{"old":"/catalog/products/:id/restore","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/restore","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/restore","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['products.restore']['types'],
  },
  'products.image.update': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/image',
    tokens: [{"old":"/catalog/products/:id/image","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/image","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/image","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/image","type":0,"val":"image","end":""}],
    types: placeholder as Registry['products.image.update']['types'],
  },
  'products.image.destroy': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/image/delete',
    tokens: [{"old":"/catalog/products/:id/image/delete","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/image/delete","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/image/delete","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/image/delete","type":0,"val":"image","end":""},{"old":"/catalog/products/:id/image/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['products.image.destroy']['types'],
  },
  'products.files.index': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products/:id/files',
    tokens: [{"old":"/catalog/products/:id/files","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/files","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/files","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['products.files.index']['types'],
  },
  'products.files.upload': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/files',
    tokens: [{"old":"/catalog/products/:id/files","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/files","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/files","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/files","type":0,"val":"files","end":""}],
    types: placeholder as Registry['products.files.upload']['types'],
  },
  'products.files.download': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products/:id/files/:fileId/download',
    tokens: [{"old":"/catalog/products/:id/files/:fileId/download","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/files/:fileId/download","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/files/:fileId/download","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/files/:fileId/download","type":0,"val":"files","end":""},{"old":"/catalog/products/:id/files/:fileId/download","type":1,"val":"fileId","end":""},{"old":"/catalog/products/:id/files/:fileId/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['products.files.download']['types'],
  },
  'products.files.destroy': {
    methods: ["POST"],
    pattern: '/catalog/products/:id/files/:fileId/delete',
    tokens: [{"old":"/catalog/products/:id/files/:fileId/delete","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/files/:fileId/delete","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/files/:fileId/delete","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/files/:fileId/delete","type":0,"val":"files","end":""},{"old":"/catalog/products/:id/files/:fileId/delete","type":1,"val":"fileId","end":""},{"old":"/catalog/products/:id/files/:fileId/delete","type":0,"val":"delete","end":""}],
    types: placeholder as Registry['products.files.destroy']['types'],
  },
  'products.qr': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products/:id/qr',
    tokens: [{"old":"/catalog/products/:id/qr","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/qr","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/qr","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/qr","type":0,"val":"qr","end":""}],
    types: placeholder as Registry['products.qr']['types'],
  },
  'products.qr.download': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/products/:id/qr/download',
    tokens: [{"old":"/catalog/products/:id/qr/download","type":0,"val":"catalog","end":""},{"old":"/catalog/products/:id/qr/download","type":0,"val":"products","end":""},{"old":"/catalog/products/:id/qr/download","type":1,"val":"id","end":""},{"old":"/catalog/products/:id/qr/download","type":0,"val":"qr","end":""},{"old":"/catalog/products/:id/qr/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['products.qr.download']['types'],
  },
  'product_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/catalog/categories',
    tokens: [{"old":"/catalog/categories","type":0,"val":"catalog","end":""},{"old":"/catalog/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['product_categories.index']['types'],
  },
  'product_categories.store': {
    methods: ["POST"],
    pattern: '/catalog/categories',
    tokens: [{"old":"/catalog/categories","type":0,"val":"catalog","end":""},{"old":"/catalog/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['product_categories.store']['types'],
  },
  'product_categories.update': {
    methods: ["POST"],
    pattern: '/catalog/categories/:id',
    tokens: [{"old":"/catalog/categories/:id","type":0,"val":"catalog","end":""},{"old":"/catalog/categories/:id","type":0,"val":"categories","end":""},{"old":"/catalog/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_categories.update']['types'],
  },
  'product_categories.archive': {
    methods: ["POST"],
    pattern: '/catalog/categories/:id/archive',
    tokens: [{"old":"/catalog/categories/:id/archive","type":0,"val":"catalog","end":""},{"old":"/catalog/categories/:id/archive","type":0,"val":"categories","end":""},{"old":"/catalog/categories/:id/archive","type":1,"val":"id","end":""},{"old":"/catalog/categories/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['product_categories.archive']['types'],
  },
  'product_categories.restore': {
    methods: ["POST"],
    pattern: '/catalog/categories/:id/restore',
    tokens: [{"old":"/catalog/categories/:id/restore","type":0,"val":"catalog","end":""},{"old":"/catalog/categories/:id/restore","type":0,"val":"categories","end":""},{"old":"/catalog/categories/:id/restore","type":1,"val":"id","end":""},{"old":"/catalog/categories/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['product_categories.restore']['types'],
  },
  'inventory.index': {
    methods: ["GET","HEAD"],
    pattern: '/inventory',
    tokens: [{"old":"/inventory","type":0,"val":"inventory","end":""}],
    types: placeholder as Registry['inventory.index']['types'],
  },
  'inventory.adjust': {
    methods: ["POST"],
    pattern: '/inventory/adjustments',
    tokens: [{"old":"/inventory/adjustments","type":0,"val":"inventory","end":""},{"old":"/inventory/adjustments","type":0,"val":"adjustments","end":""}],
    types: placeholder as Registry['inventory.adjust']['types'],
  },
  'purchases.index': {
    methods: ["GET","HEAD"],
    pattern: '/purchases',
    tokens: [{"old":"/purchases","type":0,"val":"purchases","end":""}],
    types: placeholder as Registry['purchases.index']['types'],
  },
  'purchases.show': {
    methods: ["GET","HEAD"],
    pattern: '/purchases/:id',
    tokens: [{"old":"/purchases/:id","type":0,"val":"purchases","end":""},{"old":"/purchases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['purchases.show']['types'],
  },
  'purchases.store': {
    methods: ["POST"],
    pattern: '/purchases',
    tokens: [{"old":"/purchases","type":0,"val":"purchases","end":""}],
    types: placeholder as Registry['purchases.store']['types'],
  },
  'purchases.confirm': {
    methods: ["POST"],
    pattern: '/purchases/:id/confirm',
    tokens: [{"old":"/purchases/:id/confirm","type":0,"val":"purchases","end":""},{"old":"/purchases/:id/confirm","type":1,"val":"id","end":""},{"old":"/purchases/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['purchases.confirm']['types'],
  },
  'purchases.cancel': {
    methods: ["POST"],
    pattern: '/purchases/:id/cancel',
    tokens: [{"old":"/purchases/:id/cancel","type":0,"val":"purchases","end":""},{"old":"/purchases/:id/cancel","type":1,"val":"id","end":""},{"old":"/purchases/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['purchases.cancel']['types'],
  },
  'jobs.index': {
    methods: ["GET","HEAD"],
    pattern: '/jobs',
    tokens: [{"old":"/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.index']['types'],
  },
  'jobs.show': {
    methods: ["GET","HEAD"],
    pattern: '/jobs/:id',
    tokens: [{"old":"/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.show']['types'],
  },
  'jobs.store': {
    methods: ["POST"],
    pattern: '/jobs',
    tokens: [{"old":"/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.store']['types'],
  },
  'jobs.start': {
    methods: ["POST"],
    pattern: '/jobs/:id/start',
    tokens: [{"old":"/jobs/:id/start","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/start","type":1,"val":"id","end":""},{"old":"/jobs/:id/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['jobs.start']['types'],
  },
  'jobs.pause': {
    methods: ["POST"],
    pattern: '/jobs/:id/pause',
    tokens: [{"old":"/jobs/:id/pause","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/pause","type":1,"val":"id","end":""},{"old":"/jobs/:id/pause","type":0,"val":"pause","end":""}],
    types: placeholder as Registry['jobs.pause']['types'],
  },
  'jobs.resume': {
    methods: ["POST"],
    pattern: '/jobs/:id/resume',
    tokens: [{"old":"/jobs/:id/resume","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/resume","type":1,"val":"id","end":""},{"old":"/jobs/:id/resume","type":0,"val":"resume","end":""}],
    types: placeholder as Registry['jobs.resume']['types'],
  },
  'jobs.skipStage': {
    methods: ["POST"],
    pattern: '/jobs/:id/skip-stage',
    tokens: [{"old":"/jobs/:id/skip-stage","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/skip-stage","type":1,"val":"id","end":""},{"old":"/jobs/:id/skip-stage","type":0,"val":"skip-stage","end":""}],
    types: placeholder as Registry['jobs.skipStage']['types'],
  },
  'jobs.consume': {
    methods: ["POST"],
    pattern: '/jobs/:id/consumptions',
    tokens: [{"old":"/jobs/:id/consumptions","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/consumptions","type":1,"val":"id","end":""},{"old":"/jobs/:id/consumptions","type":0,"val":"consumptions","end":""}],
    types: placeholder as Registry['jobs.consume']['types'],
  },
  'jobs.expense': {
    methods: ["POST"],
    pattern: '/jobs/:id/expenses',
    tokens: [{"old":"/jobs/:id/expenses","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/expenses","type":1,"val":"id","end":""},{"old":"/jobs/:id/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['jobs.expense']['types'],
  },
  'jobs.confirm': {
    methods: ["POST"],
    pattern: '/jobs/:id/confirm',
    tokens: [{"old":"/jobs/:id/confirm","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/confirm","type":1,"val":"id","end":""},{"old":"/jobs/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['jobs.confirm']['types'],
  },
  'jobs.fail': {
    methods: ["POST"],
    pattern: '/jobs/:id/fail',
    tokens: [{"old":"/jobs/:id/fail","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/fail","type":1,"val":"id","end":""},{"old":"/jobs/:id/fail","type":0,"val":"fail","end":""}],
    types: placeholder as Registry['jobs.fail']['types'],
  },
  'jobs.cancel': {
    methods: ["POST"],
    pattern: '/jobs/:id/cancel',
    tokens: [{"old":"/jobs/:id/cancel","type":0,"val":"jobs","end":""},{"old":"/jobs/:id/cancel","type":1,"val":"id","end":""},{"old":"/jobs/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['jobs.cancel']['types'],
  },
  'printers.index': {
    methods: ["GET","HEAD"],
    pattern: '/printers',
    tokens: [{"old":"/printers","type":0,"val":"printers","end":""}],
    types: placeholder as Registry['printers.index']['types'],
  },
  'printers.new': {
    methods: ["GET","HEAD"],
    pattern: '/printers/new',
    tokens: [{"old":"/printers/new","type":0,"val":"printers","end":""},{"old":"/printers/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['printers.new']['types'],
  },
  'printers.store': {
    methods: ["POST"],
    pattern: '/printers',
    tokens: [{"old":"/printers","type":0,"val":"printers","end":""}],
    types: placeholder as Registry['printers.store']['types'],
  },
  'printers.show': {
    methods: ["GET","HEAD"],
    pattern: '/printers/:id',
    tokens: [{"old":"/printers/:id","type":0,"val":"printers","end":""},{"old":"/printers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['printers.show']['types'],
  },
  'printers.update': {
    methods: ["POST"],
    pattern: '/printers/:id',
    tokens: [{"old":"/printers/:id","type":0,"val":"printers","end":""},{"old":"/printers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['printers.update']['types'],
  },
  'printers.retire': {
    methods: ["POST"],
    pattern: '/printers/:id/retire',
    tokens: [{"old":"/printers/:id/retire","type":0,"val":"printers","end":""},{"old":"/printers/:id/retire","type":1,"val":"id","end":""},{"old":"/printers/:id/retire","type":0,"val":"retire","end":""}],
    types: placeholder as Registry['printers.retire']['types'],
  },
  'printers.maintenance': {
    methods: ["POST"],
    pattern: '/printers/:id/maintenance',
    tokens: [{"old":"/printers/:id/maintenance","type":0,"val":"printers","end":""},{"old":"/printers/:id/maintenance","type":1,"val":"id","end":""},{"old":"/printers/:id/maintenance","type":0,"val":"maintenance","end":""}],
    types: placeholder as Registry['printers.maintenance']['types'],
  },
  'printers.expense': {
    methods: ["POST"],
    pattern: '/printers/:id/expense',
    tokens: [{"old":"/printers/:id/expense","type":0,"val":"printers","end":""},{"old":"/printers/:id/expense","type":1,"val":"id","end":""},{"old":"/printers/:id/expense","type":0,"val":"expense","end":""}],
    types: placeholder as Registry['printers.expense']['types'],
  },
  'quotations.index': {
    methods: ["GET","HEAD"],
    pattern: '/quotations',
    tokens: [{"old":"/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['quotations.index']['types'],
  },
  'quotations.show': {
    methods: ["GET","HEAD"],
    pattern: '/quotations/:id',
    tokens: [{"old":"/quotations/:id","type":0,"val":"quotations","end":""},{"old":"/quotations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quotations.show']['types'],
  },
  'quotations.store': {
    methods: ["POST"],
    pattern: '/quotations',
    tokens: [{"old":"/quotations","type":0,"val":"quotations","end":""}],
    types: placeholder as Registry['quotations.store']['types'],
  },
  'quotations.send': {
    methods: ["POST"],
    pattern: '/quotations/:id/send',
    tokens: [{"old":"/quotations/:id/send","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/send","type":1,"val":"id","end":""},{"old":"/quotations/:id/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['quotations.send']['types'],
  },
  'quotations.accept': {
    methods: ["POST"],
    pattern: '/quotations/:id/accept',
    tokens: [{"old":"/quotations/:id/accept","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/accept","type":1,"val":"id","end":""},{"old":"/quotations/:id/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['quotations.accept']['types'],
  },
  'quotations.reject': {
    methods: ["POST"],
    pattern: '/quotations/:id/reject',
    tokens: [{"old":"/quotations/:id/reject","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/reject","type":1,"val":"id","end":""},{"old":"/quotations/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['quotations.reject']['types'],
  },
  'quotations.convert': {
    methods: ["POST"],
    pattern: '/quotations/:id/convert',
    tokens: [{"old":"/quotations/:id/convert","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/convert","type":1,"val":"id","end":""},{"old":"/quotations/:id/convert","type":0,"val":"convert","end":""}],
    types: placeholder as Registry['quotations.convert']['types'],
  },
  'quotations.suggest_price': {
    methods: ["POST"],
    pattern: '/quotations/suggest-price',
    tokens: [{"old":"/quotations/suggest-price","type":0,"val":"quotations","end":""},{"old":"/quotations/suggest-price","type":0,"val":"suggest-price","end":""}],
    types: placeholder as Registry['quotations.suggest_price']['types'],
  },
  'quotations.download': {
    methods: ["GET","HEAD"],
    pattern: '/quotations/:id/download',
    tokens: [{"old":"/quotations/:id/download","type":0,"val":"quotations","end":""},{"old":"/quotations/:id/download","type":1,"val":"id","end":""},{"old":"/quotations/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['quotations.download']['types'],
  },
  'sales.index': {
    methods: ["GET","HEAD"],
    pattern: '/sales',
    tokens: [{"old":"/sales","type":0,"val":"sales","end":""}],
    types: placeholder as Registry['sales.index']['types'],
  },
  'sales.show': {
    methods: ["GET","HEAD"],
    pattern: '/sales/:id',
    tokens: [{"old":"/sales/:id","type":0,"val":"sales","end":""},{"old":"/sales/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sales.show']['types'],
  },
  'sales.store': {
    methods: ["POST"],
    pattern: '/sales',
    tokens: [{"old":"/sales","type":0,"val":"sales","end":""}],
    types: placeholder as Registry['sales.store']['types'],
  },
  'sales.confirm': {
    methods: ["POST"],
    pattern: '/sales/:id/confirm',
    tokens: [{"old":"/sales/:id/confirm","type":0,"val":"sales","end":""},{"old":"/sales/:id/confirm","type":1,"val":"id","end":""},{"old":"/sales/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['sales.confirm']['types'],
  },
  'sales.cancel': {
    methods: ["POST"],
    pattern: '/sales/:id/cancel',
    tokens: [{"old":"/sales/:id/cancel","type":0,"val":"sales","end":""},{"old":"/sales/:id/cancel","type":1,"val":"id","end":""},{"old":"/sales/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['sales.cancel']['types'],
  },
  'invoices.index': {
    methods: ["GET","HEAD"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices.index']['types'],
  },
  'invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoices.show']['types'],
  },
  'invoices.pay': {
    methods: ["POST"],
    pattern: '/invoices/:id/payments',
    tokens: [{"old":"/invoices/:id/payments","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/payments","type":1,"val":"id","end":""},{"old":"/invoices/:id/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['invoices.pay']['types'],
  },
  'invoices.void': {
    methods: ["POST"],
    pattern: '/invoices/:id/void',
    tokens: [{"old":"/invoices/:id/void","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/void","type":1,"val":"id","end":""},{"old":"/invoices/:id/void","type":0,"val":"void","end":""}],
    types: placeholder as Registry['invoices.void']['types'],
  },
  'invoices.download': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id/download',
    tokens: [{"old":"/invoices/:id/download","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/download","type":1,"val":"id","end":""},{"old":"/invoices/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['invoices.download']['types'],
  },
  'pos.index': {
    methods: ["GET","HEAD"],
    pattern: '/pos',
    tokens: [{"old":"/pos","type":0,"val":"pos","end":""}],
    types: placeholder as Registry['pos.index']['types'],
  },
  'pos.sell': {
    methods: ["POST"],
    pattern: '/pos/sell',
    tokens: [{"old":"/pos/sell","type":0,"val":"pos","end":""},{"old":"/pos/sell","type":0,"val":"sell","end":""}],
    types: placeholder as Registry['pos.sell']['types'],
  },
  'reports.profit': {
    methods: ["GET","HEAD"],
    pattern: '/reports/profit',
    tokens: [{"old":"/reports/profit","type":0,"val":"reports","end":""},{"old":"/reports/profit","type":0,"val":"profit","end":""}],
    types: placeholder as Registry['reports.profit']['types'],
  },
  'reports.inventory': {
    methods: ["GET","HEAD"],
    pattern: '/reports/inventory',
    tokens: [{"old":"/reports/inventory","type":0,"val":"reports","end":""},{"old":"/reports/inventory","type":0,"val":"inventory","end":""}],
    types: placeholder as Registry['reports.inventory']['types'],
  },
  'reports.jobs': {
    methods: ["GET","HEAD"],
    pattern: '/reports/jobs',
    tokens: [{"old":"/reports/jobs","type":0,"val":"reports","end":""},{"old":"/reports/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['reports.jobs']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
